version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=ecommerce
    volumes:
      - ./data:/var/lib/postgresql/data
